### ISSUE TITLE
Pagination-get data from all the pages 

### ISSUE THREAD

**Issue by AnneshaChowdhury** [singer-io/tap-gitlab#11]
Is there a way to get the data ( auto-pagination) from all the pages of each project, or other related events associated to project?

**Comment by nick-mccoy** [comment]
Hi @AnneshaChowdhury -- it looks like tap-gitlab is paginating:
https://github.com/singer-io/tap-gitlab/blob/a2c9141e5002875aaec8cc481f00d5a20c304c6c/tap_gitlab/__init__.py#L125

Can you be more specific about what functionality you are requesting?

**Comment by AnneshaChowdhury** [comment]
@nick-mccoy Yeah , Thanks for pointing that out!
